import os

DATA_DIR = os.getcwd() + "/../data/"

DONNEES_INITIALES = DATA_DIR + "jeu2.txt"

NOMBRE_ITERATIONS = 3000

ALPHA = .001

NOMBRE_EXECUTIONS = 15
AFFICHAGE_NOM_ALGORITHME = True
AFFICHAGE_DONNEES_PROBLEME = True
AFFICHAGE_HEURISTIQUE = True
AFFICHAGE_T = 0 # + NOMBRE_ITERATIONS
AFFICHAGE_NOUVEAU_VOISIN = False
AFFICHAGE_VOISIN_CHOISI = False
AFFICHAGE_RESULTAT = True
AFFICHAGE_STAT = False